# "ftcli" followed by ("run" or "build" etc.)

name = "push_swap"

[scripts]
build = { cmd = "make" }
run = [
  { cmd = "./push_swap 8 2 -2 0 2147483647" },
  { cmd = "./push_swap invalid" },
]

# clean = { cmd = "make fclean", mlx = true, mlx_dir = "minilibx" }
# lint = { cmd = "norm ." }